language: node_js
node_js:
  - "9"
dist: trusty

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $CI_TRAVIS  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: build
  on:
    branch: master

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - npm run build